---
- name: load variables
  include_vars: "main.yml"

- name: create greenpithumb group
  group:
    name: "{{ greenpithumb_group }}"
    state: "present"

- name: create greenpithumb user
  user:
    name: "{{ greenpithumb_user }}"
    group: "{{ greenpithumb_group }}"
    system: "yes"

- name: install necessary packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - build-essential
    - git
    - python-dev
    - python-openssl
    - python-pip

- name: install libraries
  pip:
    name: "{{ item }}"
  with_items:
    - adafruit-mcp3008
    - RPi.GPIO

- name: download Adafruit DHT library
  git:
    repo: https://github.com/adafruit/Adafruit_Python_DHT
    version: master
    dest: "{{ __greenpithumb_adafruit_dht_tmp_path }}"
  notify:
    - install Adafruit DHT library

# The Adafruit DHT library will refuse to install on non SBC machines, so if
# the target machine is not ARM-based, assume this is an install on a test
# machine and add the force test parameter.
- name: set Adafruit DHT library test compatibility
  set_fact:
    adafruit_dht_extra_args: "--force-test"
  when: "'arm' not in ansible_machine"

- name: download greenpithumb backend code
  git:
    repo: "{{ greenpithumb_git_repo }}"
    dest: "{{ greenpithumb_backend_path }}"
    version: "{{ greenpithumb_git_version }}"

- name: set greenpithumb file permissions
  file:
    path: "{{ greenpithumb_backend_path }}"
    owner: "{{ greenpithumb_user }}"
    group: "{{ greenpithumb_group }}"
    recurse: yes
    state: directory

- name: install greenpithumb dependencies
  pip:
    requirements: "{{ greenpithumb_backend_path }}/requirements.txt"

- name: create wiring config
  copy:
    src: "{{ greenpithumb_backend_path }}/greenpithumb/wiring_config.ini.example"
    dest: "{{ greenpithumb_backend_path }}/greenpithumb/wiring_config.ini"
    owner: "{{ greenpithumb_user }}"
    group: "{{ greenpithumb_group }}"
    mode: 0444
    remote_src: yes
